### ISSUE TITLE
Think a decorator would be useful?

### ISSUE THREAD

**Issue by shaunvxc** [joealcorn/laboratory#4]
Something like:
```python

def candidate_impl(x):
    # does work & returns some data

@experiment(candidate=candidate_impl)
def control_impl(x):
    # original implementation
```

If you think this would be worth supporting, let me know and I can submit a PR

**Comment by joealcorn** [comment]
It's definitely something that I'd like to have, it's simple and probably useful in a lot of cases, so go ahead with a PR if you'd like!
