### ISSUE TITLE
More informative __repr__?

### ISSUE THREAD

**Issue by spatrik** [joealcorn/laboratory#6]
I'm trying out laboratory for a project and when experimenting with it, I find the output from `print result` pretty non-informative. I've monkeypatched Result and Observation in our tests to return something like 

    Result(match=True, control=Observation(name=Control, value=<Item: Second / Default / >), observations=[Observation(name=Candidate, value=<Item: Second / Default / >)])

Would you be interested in a PR adding this into laboratory?

**Comment by joealcorn** [comment]
Absolutely, that's definitely helpful!
